# --- Шрифты и поддержка иконок (Nerd Fonts) ---
font_family      JetBrains Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

# --- Прозрачность окна ---
background_opacity 0.3

# --- Закрытие окна без подтверждения ---
confirm_os_window_close 0

# --- Автозапуск fastfetch при старте ---
shell bash -c "fastfetch --config ~/.config/fastfetch/config.jsonc; exec bash"

# --- Размытие заднего фона (Blur) ---
background_blur 20

# --- Внутренние отступы для имитации закругления ---
window_padding_width 15
